import Phaser from "phaser";
import { Client, getStateCallbacks, Room } from "colyseus.js";
import "./style.css";

const WIDTH=1280,HEIGHT=720,WORLD={x:70,y:100,w:930,h:540};
type RemotePlayer={x:number;y:number;team:string;name:string;kills:number;lives:number;alive:boolean;weapon:string;body:Phaser.GameObjects.Arc;halo:Phaser.GameObjects.Arc;label:Phaser.GameObjects.Text;};
class ArenaScene extends Phaser.Scene {
 private room!:Room; private players=new Map<string,RemotePlayer>(); private keys!:Record<string,Phaser.Input.Keyboard.Key>; private rank!:Phaser.GameObjects.Text; private status!:Phaser.GameObjects.Text; private clock!:Phaser.GameObjects.Text; private event!:Phaser.GameObjects.Text; private feed!:Phaser.GameObjects.Text; private connected=false; private voteText!:Phaser.GameObjects.Text; private overlay!:Phaser.GameObjects.Rectangle; private touch?:HTMLDivElement;

 constructor(){super("ArenaScene");}
 async create(){this.drawArena();this.makeHud();this.makeKeys();this.makeTouch();await this.connect();}
 private drawArena(){this.cameras.main.setBackgroundColor("#09080c");const g=this.add.graphics();g.fillStyle(0x151119,1);g.fillRect(0,0,WIDTH,HEIGHT);g.fillStyle(0x211b25,1);g.fillRect(WORLD.x,WORLD.y,WORLD.w,WORLD.h);g.lineStyle(3,0x4b3d4b,1);for(let x=WORLD.x+45;x<WORLD.x+WORLD.w;x+=150)g.strokeRect(x,WORLD.y+28,92,WORLD.h-56);for(let y=WORLD.y+130;y<WORLD.y+WORLD.h;y+=150)g.lineBetween(WORLD.x+25,y,WORLD.x+WORLD.w-25,y);g.lineStyle(2,0x6b526c,.5);g.strokeRect(WORLD.x+8,WORLD.y+8,WORLD.w-16,WORLD.h-16);}
 private makeHud(){this.add.text(32,22,"ARENA STREAM",{fontFamily:"system-ui",fontSize:"28px",color:"#f1e8d8",fontStyle:"bold"});this.status=this.add.text(32,60,"جاري الاتصال...",{fontFamily:"system-ui",fontSize:"15px",color:"#a99fac"});const top=this.add.graphics();top.fillStyle(0x100d14,.95);top.fillRoundedRect(430,18,330,62,12);this.clock=this.add.text(448,30,"15:00",{fontFamily:"monospace",fontSize:"30px",color:"#f4ead9",fontStyle:"bold"});this.event=this.add.text(570,40,"تصويت الجمهور بعد 05:00",{fontFamily:"system-ui",fontSize:"13px",color:"#c8bdc9"});const side=this.add.graphics();side.fillStyle(0x100d14,.94);side.fillRoundedRect(1020,18,228,390,14);this.add.text(1042,36,"الترتيب — القتلات",{fontFamily:"system-ui",fontSize:"18px",color:"#f1e8d8",fontStyle:"bold"});this.rank=this.add.text(1042,72,"بانتظار اللاعبين...",{fontFamily:"monospace",fontSize:"13px",color:"#d6ced8",lineSpacing:5});this.add.text(1020,430,"آخر الأحداث",{fontFamily:"system-ui",fontSize:"16px",color:"#f1e8d8",fontStyle:"bold"});this.feed=this.add.text(1020,458,"",{fontFamily:"system-ui",fontSize:"12px",color:"#aaa1ad",lineSpacing:7,wordWrap:{width:228}});this.voteText=this.add.text(1020,560,"",{fontFamily:"system-ui",fontSize:"12px",color:"#d7c9df",lineSpacing:6,wordWrap:{width:228}});this.add.text(32,662,"WASD للحركة • SPACE للهجوم • E لتبديل السلاح • 1/2/3 للتصويت",{fontFamily:"system-ui",fontSize:"14px",color:"#938895"});}
 private makeKeys(){if(!this.input.keyboard)return;this.keys={up:this.input.keyboard.addKey("W"),down:this.input.keyboard.addKey("S"),left:this.input.keyboard.addKey("A"),right:this.input.keyboard.addKey("D"),attack:this.input.keyboard.addKey("SPACE"),weapon:this.input.keyboard.addKey("E"),vote1:this.input.keyboard.addKey("ONE"),vote2:this.input.keyboard.addKey("TWO"),vote3:this.input.keyboard.addKey("THREE")};}
 private makeTouch(){
   const wrap=document.createElement("div");wrap.style.cssText="position:fixed;inset:0;pointer-events:none;z-index:20";
   const btn=(txt:string,right:string,bottom:string,fn:()=>void)=>{const b=document.createElement("button");b.textContent=txt;b.style.cssText=`position:absolute;right:${right};bottom:${bottom};width:62px;height:62px;border-radius:50%;border:1px solid #ffffff33;background:#120f18cc;color:#fff;font-size:22px;pointer-events:auto`;b.onpointerdown=e=>{e.preventDefault();fn()};wrap.appendChild(b);};
   btn("⚔","105px","105px",()=>this.room?.send("attack"));btn("↻","35px","105px",()=>this.room?.send("weapon"));btn("1","105px","35px",()=>this.room?.send("vote",{option:1}));btn("2","35px","35px",()=>this.room?.send("vote",{option:2}));btn("3","175px","35px",()=>this.room?.send("vote",{option:3}));
   const joy=document.createElement("div");joy.style.cssText="position:absolute;left:28px;bottom:35px;width:135px;height:135px;border-radius:50%;border:1px solid #ffffff33;background:#120f18aa;pointer-events:auto";
   const knob=document.createElement("div");knob.style.cssText="position:absolute;left:42px;top:42px;width:50px;height:50px;border-radius:50%;background:#ffffff22";joy.appendChild(knob);wrap.appendChild(joy);
   let active=false;const move=(e:PointerEvent)=>{if(!active)return;const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,len=Math.hypot(dx,dy)||1,n=Math.min(42,len);knob.style.transform=`translate(${dx/len*n}px,${dy/len*n}px)`;this.room?.send("input",{up:dy<-18,down:dy>18,left:dx<-18,right:dx>18});};joy.onpointerdown=e=>{active=true;(e.target as HTMLElement).setPointerCapture(e.pointerId);move(e as PointerEvent)};joy.onpointermove=e=>move(e as PointerEvent);joy.onpointerup=()=>{active=false;knob.style.transform="";this.room?.send("input",{up:false,down:false,left:false,right:false});};document.body.appendChild(wrap);this.touch=wrap;
 }
 private async connect(){try{const client=new Client((globalThis as any).__ARENA_SERVER_URL__||"ws://localhost:2567");const name=new URLSearchParams(location.search).get("name")||`Player-${Math.floor(100+Math.random()*900)}`;this.room=await client.joinOrCreate("arena",{name});this.connected=true;this.status.setText(`متصل • ${this.room.sessionId.slice(0,6)}`);const $=getStateCallbacks(this.room);$(this.room.state).players.onAdd((p,id)=>this.addRemote(p,id));$(this.room.state).players.onRemove((_p,id)=>this.removeRemote(id));this.room.onMessage("round-result",(top)=>this.feed.setText("القادة للجولة القادمة:\n"+top.map((p:any)=>`${p.name} • ${p.kills} قتلات`).join("\n"));this.room.onMessage("attack-fx",(fx:any)=>this.fx(fx));this.room.onMessage("kill-fx",(fx:any)=>this.killFx(fx));this.room.onMessage("trap-fx",(fx:any)=>this.trapFx(fx));}catch(e){this.status.setText("السيرفر غير متصل — شغّل server أولاً");console.error(e);}}
 private addRemote(p:any,id:string){const team=p.team==="A";const halo=this.add.circle(p.x,p.y,31,team?0x9b59ff:0x45d6e8,.13);const body=this.add.circle(p.x,p.y,17,0x0e0d12,1);this.add.circle(p.x,p.y,10,team?0xb77cff:0x66e7f5,.85);const label=this.add.text(p.x,p.y-49,p.name||"Player",{fontFamily:"monospace",fontSize:"12px",color:"#eee7f0",backgroundColor:"#0b0910",padding:{x:5,y:3}}).setOrigin(.5);this.players.set(id,{x:p.x,y:p.y,team:p.team,name:p.name,kills:p.kills,lives:p.lives,alive:p.alive,weapon:p.weapon,body,halo,label});}
 private removeRemote(id:string){const p=this.players.get(id);if(!p)return;p.body.destroy();p.halo.destroy();p.label.destroy();this.players.delete(id);}
 private fx(f:any){const line=this.add.graphics();line.lineStyle(f.weapon==="bow"?3:7,f.weapon==="bow"?0xf5d76e:0xe8d9ff,.9);line.lineBetween(f.x1,f.y1,f.x2,f.y2);this.tweens.add({targets:line,alpha:0,duration:160,onComplete:()=>line.destroy()});if(f.weapon==="bow"){const a=this.add.circle(f.x2,f.y2,4,0xf5d76e,1);this.tweens.add({targets:a,alpha:0,x:f.x2,y:f.y2,duration:180,onComplete:()=>a.destroy()});}}
 private killFx(f:any){const t=this.add.text(f.x,f.y-28,"✦",{fontSize:"28px",color:"#fff"}).setOrigin(.5);this.tweens.add({targets:t,y:f.y-70,alpha:0,duration:550,onComplete:()=>t.destroy()});}
 private trapFx(f:any){const c=this.add.circle(f.x,f.y,22,0xff7744,.3);this.tweens.add({targets:c,scale:2,alpha:0,duration:350,onComplete:()=>c.destroy()});}
 update(){if(!this.connected)return;const k=this.keys;this.room.send("input",{up:k.up.isDown,down:k.down.isDown,left:k.left.isDown,right:k.right.isDown});if(Phaser.Input.Keyboard.JustDown(k.attack))this.room.send("attack");if(Phaser.Input.Keyboard.JustDown(k.weapon))this.room.send("weapon");if(Phaser.Input.Keyboard.JustDown(k.vote1))this.room.send("vote",{option:1});if(Phaser.Input.Keyboard.JustDown(k.vote2))this.room.send("vote",{option:2});if(Phaser.Input.Keyboard.JustDown(k.vote3))this.room.send("vote",{option:3});const s:any=this.room.state;const secs=Math.ceil(s.remainingMs/1000);this.clock.setText(`${String(Math.floor(secs/60)).padStart(2,"0")}:${String(secs%60).padStart(2,"0")}`);const es=Math.ceil(s.eventRemainingMs/1000);this.event.setText(`الجمهور بعد ${String(Math.floor(es/60)).padStart(2,"0")} • ${s.activeEvent||"—"}`);if(s.lastKill)this.feed.setText(s.lastKill);this.voteText.setText(`تصويت الجمهور:\n1) ${s.vote1||"—"} (${s.votes1||0})\n2) ${s.vote2||"—"} (${s.votes2||0})\n3) ${s.vote3||"—"} (${s.votes3||0})`);const sorted:any[]=[];s.players.forEach((p:any,id:string)=>{const r=this.players.get(id);if(!r)return;r.x=p.x;r.y=p.y;r.kills=p.kills;r.lives=p.lives;r.alive=p.alive;r.body.setPosition(p.x,p.y).setVisible(p.alive);r.halo.setPosition(p.x,p.y).setVisible(p.alive);r.label.setPosition(p.x,p.y-49).setVisible(p.alive);sorted.push(p);});sorted.sort((a,b)=>b.kills-a.kills);this.rank.setText(sorted.map((p,i)=>`${String(i+1).padStart(2," ")}. ${p.name} ⚔ ${p.kills} ♥ ${p.lives}`).join("\n"));if(s.darkness)this.overlay=this.overlay||this.add.rectangle(WIDTH/2,HEIGHT/2,WIDTH,HEIGHT,0x000000,.72).setDepth(50);else if(this.overlay){this.overlay.destroy();this.overlay=undefined;}}
}
new Phaser.Game({type:Phaser.AUTO,parent:"game",width:WIDTH,height:HEIGHT,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},render:{antialias:true},scene:[ArenaScene]});
