import Phaser from "phaser";
import { Client, getStateCallbacks, Room } from "colyseus.js";
import "./style.css";
const WIDTH=1280,HEIGHT=720,WORLD={x:70,y:100,w:930,h:540};
type RemotePlayer={x:number;y:number;team:string;name:string;kills:number;lives:number;alive:boolean;weapon:string;body:Phaser.GameObjects.Arc;halo:Phaser.GameObjects.Arc;label:Phaser.GameObjects.Text};
class ArenaScene extends Phaser.Scene {
 private room!:Room; private players=new Map<string,RemotePlayer>(); private keys!:Record<string,Phaser.Input.Keyboard.Key>; private rank!:Phaser.GameObjects.Text; private status!:Phaser.GameObjects.Text; private clock!:Phaser.GameObjects.Text; private event!:Phaser.GameObjects.Text; private feed!:Phaser.GameObjects.Text; private connected=false; private voteText!:Phaser.GameObjects.Text;
 constructor(){super("ArenaScene");}
 async create(){this.drawArena();this.makeHud();this.makeKeys();await this.connect();}
 private drawArena(){this.cameras.main.setBackgroundColor("#09080c");const g=this.add.graphics();g.fillStyle(0x151119,1);g.fillRect(0,0,WIDTH,HEIGHT);g.fillStyle(0x211b25,1);g.fillRect(WORLD.x,WORLD.y,WORLD.w,WORLD.h);g.lineStyle(3,0x4b3d4b,1);for(let x=WORLD.x+45;x<WORLD.x+WORLD.w;x+=150)g.strokeRect(x,WORLD.y+28,92,WORLD.h-56);for(let y=WORLD.y+130;y<WORLD.y+WORLD.h;y+=150)g.lineBetween(WORLD.x+25,y,WORLD.x+WORLD.w-25,y);g.lineStyle(2,0x6b526c,.5);g.strokeRect(WORLD.x+8,WORLD.y+8,WORLD.w-16,WORLD.h-16);}
 private makeHud(){this.add.text(32,22,"ARENA STREAM",{fontFamily:"system-ui",fontSize:"28px",color:"#f1e8d8",fontStyle:"bold"});this.status=this.add.text(32,60,"جاري الاتصال...",{fontFamily:"system-ui",fontSize:"15px",color:"#a99fac"});const top=this.add.graphics();top.fillStyle(0x100d14,.95);top.fillRoundedRect(430,18,330,62,12);this.clock=this.add.text(448,30,"15:00",{fontFamily:"monospace",fontSize:"30px",color:"#f4ead9",fontStyle:"bold"});this.event=this.add.text(570,40,"تصويت الجمهور بعد 05:00",{fontFamily:"system-ui",fontSize:"13px",color:"#c8bdc9"});const side=this.add.graphics();side.fillStyle(0x100d14,.94);side.fillRoundedRect(1020,18,228,390,14);this.add.text(1042,36,"الترتيب — القتلات",{fontFamily:"system-ui",fontSize:"18px",color:"#f1e8d8",fontStyle:"bold"});this.rank=this.add.text(1042,72,"بانتظار اللاعبين...",{fontFamily:"monospace",fontSize:"13px",color:"#d6ced8",lineSpacing:5});this.add.text(1020,430,"آخر الأحداث",{fontFamily:"system-ui",fontSize:"16px",color:"#f1e8d8",fontStyle:"bold"});this.feed=this.add.text(1020,458,"",{fontFamily:"system-ui",fontSize:"12px",color:"#aaa1ad",lineSpacing:7,wordWrap:{width:228}});this.voteText=this.add.text(1020,560,"",{fontFamily:"system-ui",fontSize:"12px",color:"#d7c9df",lineSpacing:6,wordWrap:{width:228}});this.add.text(32,662,"WASD للحركة • SPACE للهجوم • E لتبديل السلاح",{fontFamily:"system-ui",fontSize:"14px",color:"#938895"});}
 private makeKeys(){if(!this.input.keyboard)return;this.keys={up:this.input.keyboard.addKey("W"),down:this.input.keyboard.addKey("S"),left:this.input.keyboard.addKey("A"),right:this.input.keyboard.addKey("D"),attack:this.input.keyboard.addKey("SPACE"),weapon:this.input.keyboard.addKey("E"),vote1:this.input.keyboard.addKey("ONE"),vote2:this.input.keyboard.addKey("TWO"),vote3:this.input.keyboard.addKey("THREE")};}
 private async connect(){
  try{const client=new Client((globalThis as any).__ARENA_SERVER_URL__||"ws://localhost:2567");const name=new URLSearchParams(location.search).get("name")||`Player-${Math.floor(100+Math.random()*900)}`;this.room=await client.joinOrCreate("arena",{name});this.connected=true;this.status.setText(`متصل • ${this.room.sessionId.slice(0,6)}`);const $=getStateCallbacks(this.room);
   $(this.room.state).players.onAdd((p,id)=>this.addRemote(p,id));
   $(this.room.state).players.onRemove((_p,id)=>this.removeRemote(id));
   this.room.onMessage("round-result",(top)=>this.feed.setText("القادة للجولة القادمة:\n"+top.map((p:any)=>`${p.name} • ${p.kills} قتلات`).join("\n")));
  }catch(e){this.status.setText("السيرفر غير متصل — شغّل server أولاً");console.error(e);}
 }
 private addRemote(p:any,id:string){const team=p.team==="A";const halo=this.add.circle(p.x,p.y,31,team?0x9b59ff:0x45d6e8,.13);const body=this.add.circle(p.x,p.y,17,0x0e0d12,1);this.add.circle(p.x,p.y,10,team?0xb77cff:0x66e7f5,.85);const label=this.add.text(p.x,p.y-49,p.name||"Player",{fontFamily:"monospace",fontSize:"12px",color:"#eee7f0",backgroundColor:"#0b0910",padding:{x:5,y:3}}).setOrigin(.5);this.players.set(id,{x:p.x,y:p.y,team:p.team,name:p.name,kills:p.kills,lives:p.lives,alive:p.alive,weapon:p.weapon,body,halo,label});}
 private removeRemote(id:string){const p=this.players.get(id);if(!p)return;p.body.destroy();p.halo.destroy();p.label.destroy();this.players.delete(id);}
 update(){if(!this.connected)return;const k=this.keys;this.room.send("input",{up:k.up.isDown,down:k.down.isDown,left:k.left.isDown,right:k.right.isDown});if(Phaser.Input.Keyboard.JustDown(k.attack))this.room.send("attack");if(Phaser.Input.Keyboard.JustDown(k.weapon))this.room.send("weapon");if(Phaser.Input.Keyboard.JustDown(k.vote1))this.room.send("vote",{option:1});if(Phaser.Input.Keyboard.JustDown(k.vote2))this.room.send("vote",{option:2});if(Phaser.Input.Keyboard.JustDown(k.vote3))this.room.send("vote",{option:3});const s:any=this.room.state;const secs=Math.ceil(s.remainingMs/1000);this.clock.setText(`${String(Math.floor(secs/60)).padStart(2,"0")}:${String(secs%60).padStart(2,"0")}`);const es=Math.ceil(s.eventRemainingMs/1000);this.event.setText(`الجمهور بعد ${String(Math.floor(es/60)).padStart(2,"0")}:${String(es%60).padStart(2,"0")} • ${s.activeEvent||"—"}`);if(s.lastKill)this.feed.setText(s.lastKill);this.voteText.setText(`تصويت الجمهور:\n1) ${s.vote1||"—"} (${s.votes1||0})\n2) ${s.vote2||"—"} (${s.votes2||0})\n3) ${s.vote3||"—"} (${s.votes3||0})`);const sorted:any[]=[];s.players.forEach((p:any,id:string)=>{const r=this.players.get(id);if(!r)return;r.x=p.x;r.y=p.y;r.kills=p.kills;r.lives=p.lives;r.alive=p.alive;r.body.setPosition(p.x,p.y).setVisible(p.alive);r.halo.setPosition(p.x,p.y).setVisible(p.alive);r.label.setPosition(p.x,p.y-49).setVisible(p.alive);sorted.push(p);});sorted.sort((a,b)=>b.kills-a.kills);this.rank.setText(sorted.map((p,i)=>`${String(i+1).padStart(2," ")}. ${p.name} ⚔ ${p.kills} ♥ ${p.lives}`).join("\n"));}
}
new Phaser.Game({type:Phaser.AUTO,parent:"game",width:WIDTH,height:HEIGHT,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},render:{antialias:true},scene:[ArenaScene]});
